In [2]:
import numpy as np

print("NumPy Version:", np.__version__)

NumPy Version: 2.5.2


Creating numpy Array

Dimentional Array

1D Array
2D Array
3D Array
"""


1D Array

In [3]:
array_1d = np.array([10, 20, 30, 40, 50])

print("1D Array:")
print(array_1d)

1D Array:
[10 20 30 40 50]


2D Array

In [4]:
array_2d = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print("2D Array:")
print(array_2d)

2D Array:
[[10 20 30]
 [40 50 60]
 [70 80 90]]


3D Array

In [5]:
array_3d = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])

print("3D Array:")
print(array_3d)

3D Array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


Checking Dimensions, Shape, Size, and Data Type

In [6]:
print("Array:")
print(array_2d)

print("\nNumber of dimensions:", array_2d.ndim)
print("Shape:", array_2d.shape)
print("Number of elements:", array_2d.size)
print("Data type:", array_2d.dtype)

Array:
[[10 20 30]
 [40 50 60]
 [70 80 90]]

Number of dimensions: 2
Shape: (3, 3)
Number of elements: 9
Data type: int64


Creating Arrays Using zeros()

In [7]:
zeros_array = np.zeros((3, 4))

print("Array of zeros:")
print(zeros_array)

Array of zeros:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Creating Arrays Using ones()

In [8]:
ones_array = np.ones((3, 4))

print("Array of ones:")
print(ones_array)

Array of ones:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


Using arange()

In [ ]:
range_array = np.arange(1, 11)

print("Array using arange():")
print(range_array)

You can also specify a step:

In [9]:
range_array = np.arange(0, 21, 2)

print(range_array)

[ 0  2  4  6  8 10 12 14 16 18 20]


Using linspace()

In [10]:
linear_array = np.linspace(0, 1, 6)

print("Array using linspace():")
print(linear_array)

Array using linspace():
[0.  0.2 0.4 0.6 0.8 1. ]


Data Type and Casting

In [17]:
a = np.array([1, 2, 3, 4, 5.2])
print(a.dtype)

float64


Casting

In [18]:
a.astype(int)
print(a.dtype)

float64


Indexing and Slicing

In [ ]:
a = np.array([1, 2, 3, 4, 5])
print(a[2])

'''Slicing'''
print(a[1:])


3
[2 3 4 5]


Slicing in 2D array

In [ ]:
                   #0            #1
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(a[1, 2])

7


In [28]:
print(a[0, 1:])

[2 3 4]


Reshaping arrays

In [ ]:
#how to convert 1D array into 2D array

In [ ]:
a = np.arange(1, 13)
print(a)

y = a.reshape(3, 4)
print(y)
 #we Cannot reshape an array to any other shape 
 #eg : if one elemt is not there we cannote arange it

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


flatten() -> Creates a new array

In [39]:
a = np.arange(1, 13)
b = a.reshape(3, 4)
print(b)

c = b.flatten()
print(c)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


ravel() -> Create  a new  possible array"""

In [ ]:
d = a.reshape(6, -1)
print(d)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


Fancy Indexing -> meantion which particular element is need ed

In [45]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a[[0, 3, 5]])

[1 4 6]


Boolean Masking

In [47]:
a = np.array([1, 2, 3, 4, 5, 6, 7])
print (a > 5)

[False False False False False  True  True]


Masking

In [48]:
a[a > 5]

array([6, 7])

Multiple Conditions
1-and
2-or
3-not

Vectorized Operations

In [51]:
a = np.array([1, 2, 3, 4, 5])
b = a + 2
c =a * 2
print(b)
print(c)

[3 4 5 6 7]
[ 2  4  6  8 10]


BroadCasting

In [55]:
num1 = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

num2 = np.array([
    [10, 20, 30]  
])

addition = num1 + num2

print("Original array:")
print(num1)
print(num2)

print("\nAfter broadcasting 5:")
print(addition)


Original array:
[[10 20 30]
 [40 50 60]]
[[10 20 30]]

After broadcasting 5:
[[20 40 60]
 [50 70 90]]


Functions and Aggregations 
np.sqrt()
np.log()
etc....

Aggregate Functions

In [56]:
data = np.array([10, 20, 30, 40, 50])

print("Sum:", np.sum(data))
print("Mean:", np.mean(data))
print("Minimum:", np.min(data))
print("Maximum:", np.max(data))
print("Median:", np.median(data))

Sum: 150
Mean: 30.0
Minimum: 10
Maximum: 50
Median: 30.0


View() and Copy()

In [60]:
a = np.array([1, 2, 3, 4])
a[2] = 300
b= a.copy()
print(a)
print(b)

[  1   2 300   4]
[  1   2 300   4]


In [63]:
a = np.array([1, 2, 3, 4])
b = a.copy()
a[2] = 300
print(a)
print(b)

'''Copied array onve the data, any  
Changes made to orginal array  doesn't
impact copy array'''

[  1   2 300   4]
[1 2 3 4]


"Copied array onve the data, any  \nChanges made to orginal array  doesn't\nimpact copy array"

View()

In [ ]:
a = np.array([1,2,3,4])
b = a.view()
a[3] = 400
print(a)
print(b)
'''View doesn't own the data so any change
made in the Orginal array doesn't impacts View array'''

[  1   2   3 400]
[  1   2   3 400]
